#
# Copyright 2018. Gatekeeper Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

accounts:
  -
    accountId: 635262737231
    name: dev-account
    sdlc: dev
    alias: Dev
    regions:
      -
        name: us-east-1
      -
        name: us-east-2
  -
    accountId: 645378392965
    name: int-account
    sdlc: dev
    alias: INT
    regions:
      -
        name: us-east-1
      -
        name: us-east-2
  -
    accountId: 876523451928
    name: qa-account
    sdlc: qa
    alias: QA
    regions:
      -
        name: us-east-1
      -
        name: us-east-2
  -
    accountId: 918282926574
    name: prod-account
    sdlc: prod
    alias: PROD
    regions:
      -
        name: us-east-1
      -
        name: us-east-2
      -
        name: us-west-1